# permissions for end users to edit dorisclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: doris-operator
    app.kubernetes.io/managed-by: kustomize
  name: doriscluster-editor-role
rules:
- apiGroups:
  - doris.kubedoop.dev
  resources:
  - dorisclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - doris.kubedoop.dev
  resources:
  - dorisclusters/status
  verbs:
  - get
