apiVersion: doris.kubedoop.dev/v1alpha1
kind: DorisCluster
metadata:
  labels:
    app.kubernetes.io/name: doris-operator
    app.kubernetes.io/managed-by: kustomize
  name: doriscluster-sample
spec:
  frontEnd:
    roleGroups:
      default:
        replicas: 1
  backEnd:
    roleGroups:
      default:
        replicas: 1
