apiVersion: v2
name: doris-operator
description: Apache Doris operator of Kubedoop

type: application

version: 0.0.0-dev
appVersion: 0.0.0-dev

maintainers:
  - email: zncdatadev@googlegroups.com
    name: ZNCDataDev Team
