{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "doris-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "doris-operator.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "doris-operator.selectorLabels" . | nindent 6 }}
      control-plane: controller-manager
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
  - port: {{ if .Values.metrics.secure }}https{{ else }}http{{ end }}
    path: {{ .Values.serviceMonitor.path }}
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    {{- if .Values.metrics.secure }}
    tlsConfig:
      insecureSkipVerify: {{ .Values.serviceMonitor.tlsConfig.insecureSkipVerify }}
    {{- end }}
{{- end }}
